name: CI

on:
  pull_request:
  push:
    # Filtering branches here prevents duplicate builds from pull_request and push
    branches:
      - master
      - beta
      - 'v*'
      - /^greenkeeper.*$/

    # Always run CI for tags
    tags:
      - '*'

  # Early issue detection: run CI weekly on Sundays
  schedule:
  - cron:  '0 6 * * 0'

jobs:
  test-all-packages:
    name: Ember Tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16.x, 14.x, 12.x]
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Yarn Install
        run: yarn install --ignore-engines --frozen-lockfile
      - name: Run ember-cli-fastboot Tests
        run: yarn workspace ember-cli-fastboot test:ember
      - name: Run fastboot Tests
        if: ${{ matrix.os != 'windows-latest' }}
        run: yarn workspace fastboot test
      - name: Run fastboot-express-middleware Tests
        run: yarn workspace fastboot-express-middleware test
      - name: Run fastboot-app-server Tests
        run: yarn workspace fastboot-app-server test:mocha

  integration-tests:
    name: Integration Tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16.x, 14.x, 12.x]
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Yarn Install
        run: yarn install --ignore-engines --frozen-lockfile
      - name: Integration Tests
        run: yarn workspace integration-tests test

  test-packages:
    name: Test Packages
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16.x, 14.x, 12.x]
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Yarn Install
        run: yarn install --ignore-engines --frozen-lockfile
      - name: Basic App
        run: yarn workspace basic-app test:mocha
      - name: Custom App
        run: yarn workspace custom-fastboot-app test:mocha

  test-legacy-mocha:
    name: Legacy Mocha Tests - ${{ matrix.node-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: ['14', '12', '10']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: volta-cli/action@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Remove test-packages folder so that we don't leak node_modules between apps
      - name: Remove test-packages
        run: |
          rm -rf test-packages
      - name: Yarn Install
        working-directory: ./packages/ember-cli-fastboot
        run: |
          yarn install --ignore-engines --frozen-lockfile
      - name: Run Mocha Tests
        working-directory: ./packages/ember-cli-fastboot
        run: |
          npm --version
          yarn test:mocha
